spring:
  datasource:
    url:
    username:
    password:
    driver-class-name:
  data:
    redis:
      host:
      password:
      database:
      port:
      timeout:
      lettuce:
        pool:
          max-active:
          max-wait:
          max-idle:
          min-idle:
conf:
  transmission:
    url:
    authorization:
    minSizeGB:
    days:
    tempDownloadDir:
  jellyfin:
    url:
    token:
  docker:
    tcpUrl:
    apiVersion:
  qywx:
    corpid:
    token:
    encodingAeskey:
    noticeZxb:
    noticeCxy:
    agent002Id:
    agent002Secert:
    agent003Id:
    agent003Secert:
    agent004Id:
    agent004Secert:
  github:
    authorization:
  azure:
    voiceKey:
  bwg:
    apiKey:
  openai:
    apiKey:
  pdf:
    path:
  voice:
    path:
  common:
    cxyNoticeText:
    clashRssUrl:

