name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
    paths:
      - 'pom.xml'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'pom.xml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Extract project version
        id: project_version
        run: |
          echo "PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/loktar:${{ env.PROJECT_VERSION }}
          build-args: |
            JAR_FILE=target/*.jar

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: zxb0303/loktar:${{ env.PROJECT_VERSION }}
          build-args: |
            JAR_FILE=target/*.jar

#      - name: Prepare private Docker Registry tag
#        run: echo "PRIVATE_REGISTRY_TAG=${{ secrets.PRIVATE_REGISTRY_URL }}/loktar:${{ env.PROJECT_VERSION }}" >> $GITHUB_ENV
#
#      - name: Login to Private Docker Registry
#        uses: docker/login-action@v3
#        with:
#          registry: ${{ secrets.PRIVATE_REGISTRY_URL }}
#          username: ${{ secrets.PRIVATE_REGISTRY_USERNAME }}
#          password: ${{ secrets.PRIVATE_REGISTRY_PASSWORD }}
#
#      - name: Build and push Docker image to Private Docker Registry
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          file: ./Dockerfile
#          push: true
#          tags: ${{ env.PRIVATE_REGISTRY_TAG }}
#          build-args: |
#            JAR_FILE=target/*.jar

      - name: Send Webhook Notification
        run: |
          curl -X POST -d "version=loktar:${{ env.PROJECT_VERSION }}" ${{ secrets.WEB_HOOK_URL }}